---
title: "week-18"
author: "Maxwel Coura Oliveira"
date: "5/6/2022"
output: html_document
---

```{r}
capacity <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-03/capacity.csv')
wind <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-03/wind.csv')
solar <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-03/solar.csv')
average_cost <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-03/average_cost.csv')
```

```{r}
library(tidyverse)
library(ggthemes)
library(lubridate)
library(waffle)
```


```{r}
average_cost |> 
  pivot_longer(cols = 2:4, names_to = "type", values_to = "value_MWh") |> 
  mutate(type = str_remove(type, "_mwh")) |> 
  mutate(type = str_to_title(type)) -> average_cost1
```






```{r}
average_cost1 |> 
  mutate(value_MWh = as.integer(round(value_MWh, 0))) |> 
  filter(year != 2021) |> 
  ggplot(aes(fill = type, values = value_MWh)) +
  geom_waffle(color = "white", size = .25, n_rows = 10, flip = TRUE) +
  facet_wrap(~year, nrow = 1, strip.position = "bottom") +
  labs(title = "Average cost of energy in the US", 
       subtitle = "Solar energy cost dramatically decreased in the past decade",
       y = "Price (US$/MWh)",
       caption = "Source: Berkeley Lab | Figure: @maxwelco") +
  scale_x_discrete() + 
  scale_y_continuous(labels = function(x) x * 10, # make this multiplyer the same as n_rows
                     expand = c(0,0)) +
#  scale_fill_tableau(name=NULL) +
  scale_fill_colorblind(name = NULL) +
  theme_clean() +
  theme(panel.grid = element_blank(), axis.ticks.y = element_line()) +
  guides(fill = guide_legend(reverse = TRUE)) +
  theme(legend.position = c(0.95, 0.82),
        legend.background = element_rect(color = NA))

ggsave("fig_18.png", width = 9, height = 5)
```












