---
title: "week-37"
author: "Maxwel Coura Oliveira"
date: "9/7/2021"
output: html_document
---

```{r}
library(tidyverse)
```


```{r}
circuits <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/circuits.csv')
constructor_results <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/constructor_results.csv')
constructor_standings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/constructor_standings.csv')
constructors <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/constructors.csv')
driver_standings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/driver_standings.csv')
drivers <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/drivers.csv')
lap_times <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/lap_times.csv')
pit_stops <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/pit_stops.csv')
qualifying <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/qualifying.csv')
races <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/races.csv')
results <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/results.csv')
seasons <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/seasons.csv')
status <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-07/status.csv')
```


```{r}
races %>% 
  dplyr::select(-time, -url) -> races1

circuits %>% 
  dplyr::select(-url) %>% 
  rename(circuit_name = name) -> circuits1
```




```{r}
drivers %>% 
  dplyr::select(-number, -url) %>% 
  left_join(results, by = "driverId") %>% 
  left_join(races1, by = "raceId") %>% 
  left_join(status, by = "statusId") %>% 
  left_join(circuits1, by = "circuitId")
```


```{r}
filter(driverRef == "senna") %>% 
  ggplot(aes(x = grid, y = positionOrder)) +
  geom_jitter() +
  geom_smooth(method = "lm")
```


```{r}
drivers %>% 
  left_join(driver_standings, by = "driverId") %>%
  left_join(results, by = c("driverId"))
  filter(nationality == "Brazilian") %>% 
  count(driverRef, positionText) %>% 
  filter(positionText == "1")
```

