---
title: "week-31"
author: "Maxwel Coura Oliveira"
date: "7/27/2021"
output: html_document
---




```{r}
olympics <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-27/olympics.csv')
```
```{r}
olympics %>% 
  filter(noc == "BRA") %>% 
  filter(!is.na(medal)) %>% 
  distinct(games, event, medal) %>% 
  count(medal)
```


```{r}
library(tidyverse)
library(reactablefmtr)
library(ggflags)
```

```{r}
mobile <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-11-10/mobile.csv') %>% 
  dplyr::select(entity, continent) %>% 
  filter(continent == "Americas") -> country

country
```

  filter(!is.na(medal)) %>% 
```{r}
country %>% 
  left_join(olympics, by = c("entity" = "team")) %>% 
  filter(!entity %in% c("United States", "Canada") & season == "Summer") %>% 
  filter(!is.na(medal)) %>% 
  distinct(entity, games, event, medal) %>% 
  count(entity, medal) -> latin_am
```


```{r}
latin_am %>% 
  pivot_wider(id_cols = entity, names_from = medal, values_from = n) %>% 
  mutate_at(c("Bronze", "Gold", "Silver"), ~ replace_na(., 0)) %>% 
  mutate(Total = Gold + Silver + Bronze) %>% 
  group_by(entity) %>% 
  arrange(desc(Gold)) %>%
  ungroup(entity) %>%
  mutate(Rank = row_number()) -> latin_am1
```

```{r}
library(countrycode) #https://github.com/vincentarelbundock/countrycode

flags <- latin_am1 %>% 
  pull(entity) 

countrycode(flags, 'country.name', 'unicode.symbol') %>% as_tibble() -> flags1

latin_am1 %>% 
  distinct(entity) %>% 
  bind_cols(flags1) %>% 
  unite("flag_country", c("value", "entity"), sep = " ") -> flag_country
```


```{r}
gold <- "https://image.flaticon.com/icons/png/512/625/625394.png"

latin_am1 %>% 
  bind_cols(flag_country) %>% 
  dplyr::select("#", flag_country, Gold, Silver, Bronze, Total) %>% 
  rename(Country = flag_country) %>% 
  reactable(.,
            theme = fivethirtyeight(),
            pagination = FALSE,
            resizable = TRUE,
            columns = list(
            Gold = colDef(name =  "Gold", width = 50))) -> medal
medal %>%
save_reactable("table.png")
```

  
```{r}
latin_am1 %>% 
#  bind_cols(flag_country) %>% 
  pivot_longer(c("Gold", "Silver", "Bronze"), 
               names_to = "medal", 
               values_to = "n") %>% 
  dplyr::select(Rank, entity, medal, n, Total) %>% 
  rename(Country = entity) -> latin_am
```

```{r}
library(extrafont)
library(showtext)
showtext_auto()
font_add_google("Lato", "lato") 
```
```{r}
countrycode(flags, 'country.name', 'iso2c') %>% 
  as_tibble() %>% 
  rename(flag = value) %>% 
  mutate(flag = str_to_lower(flag)) -> flag
```

```{r}
latin_am %>% 
  distinct(Country) %>% 
  bind_cols(flag) -> flags1

latin_am %>% 
  left_join(flags1) -> latin_am1
```


```{r}
latin_am1 %>% 
  ggplot(aes(x = Rank, y = n, 
           country = flag, 
           label = Country)) +
  geom_jitter(size = 6, width = 0.01,
              aes(color = medal), show.legend = FALSE) +
  coord_flip() +
  labs(x = NULL, y = NULL) +
  geom_flag(latin_am1 %>% 
              group_by(Country) %>% 
              filter(n == min(n)),
            mapping = aes(y = n - 10), hjust = 1) +
  scale_color_manual(values = c("#977547", "#D6AF36", "#d6d6d6")) +
  geom_text(latin_am1 %>% 
              group_by(Country) %>% 
              filter(n == min(n)),
              mapping = aes(label = Country),
            nudge_y = -15, hjust = 1, size = 5) +
  scale_x_reverse() +
  scale_y_continuous(limits = c(-75, 100), breaks = seq(0, 80, 20)) +
  theme_clean(base_family = "lato") +
  theme(axis.text.y = element_blank(),
        axis.title = element_blank())

ggsave("fig.png", bg = "white", height = 12)
```
```{r}
  geom_bar(stat = "identity", aes(fill = medal), show.legend = FALSE) +
  coord_flip() +
  scale_fill_manual(values = c("#977547", "#D6AF36", "#d6d6d6")) +
```

