---
title: "week-46"
author: "Maxwel Coura Oliveira"
date: "11/8/2021"
output: html_document
---



```{r}
#remotes::install_github("afrimapr/afrilearndata")
```

```{r}
library(afrilearndata)
library(sf)
library(ggspatial)
library(tidyverse)
library(ggtext)
```


```{r}
afrilearndata::afrihighway -> af_roads
afrilearndata::africontinent -> af
afrilearndata::africapitals -> af_capitals
```

```{r}
#library(extrafont)
library(showtext)
showtext_auto() 
font_add_google("Alegreya Sans SC", "alegreya") 
```

```{r}
af |> 
  ggplot() +
  geom_sf(color = NA, fill = "#222024") +
  geom_sf(data = af_roads, aes(color = Name), 
          show.legend = FALSE, size = 1.1) +
#  geom_sf(data = af_capitals, shape = 17, color = "#FF8866") +
  coord_sf(xlim = c(-20, 55), 
           ylim = c(-40, 40), 
           expand = FALSE) +
  theme_bw() +
  labs(caption = "Source: afrilearndata | Figure: @maxwelco") +
  scale_color_viridis_d(option = "H") +
  theme(panel.background = element_rect(fill = "aliceblue"),
        legend.position = c(0.80, 0.95),
        legend.background = element_rect(fill = NA),
        legend.direction = "horizontal",
        plot.caption = element_markdown(size = 25, family = "alegreya"),
        axis.text = element_markdown(size = 40, family = "alegreya"),
        legend.title = element_markdown(face = "bold"),
        legend.key.width = unit(2,"line")) +
  annotation_scale(location = "br", 
                   width_hint = 0.4, 
                   text_cex = 3) + 
  annotation_north_arrow(location = "tr", 
                         which_north = "true",
                         pad_x = unit(0.05, "in"),
                         pad_y = unit(0.05, "in"), 
                         style = north_arrow_nautical(text_size = 30,
                                                      text_family = "alegreya")) +
  annotate(geom = "richtext", 
           x = -3, 
           y = -20, 
           fill = NA, 
           label.color = NA,
           label = "Trans-<br>African<br> Highway<br> network", 
           fontface = "bold", 
           family = "alegreya",
           lineheight = 0.3,
           color = "#222024", 
           size = 45, 
           hjust = 0.5) 

ggsave("fig_46.png", width = 7, height = 7)
```

