---
title: "week-33"
author: "Maxwel Coura Oliveira"
date: "8/10/2021"
output: html_document
---

```{r}
library(tidyverse)
library(ggecho)
library(ggtext)
library(ggrepel)
library(hrbrthemes)
```




```{r}
tuesdata <- tidytuesdayR::tt_load(2021, week = 33)

investment <- tuesdata$investment
chain <- tuesdata$chain_investment
ipd <- tuesdata$ipd
```





```{r}
library(showtext)
library(extrafont)
library(showtext)
showtext_auto()
font_add_google("Lato", "lato")
font_add_google("Staatliches", "staatliches")
```


data = investment %>% 
                  filter(meta_cat == "Total basic infrastructure") %>% 
                  filter(max(year))
```{r message = FALSE, warning = FALSE}
options(scipen = 999)
investment %>% 
  filter(meta_cat == "Total basic infrastructure") -> investment1
```


```{r message = FALSE, warning = FALSE}
investment1 %>% 
  ggplot(aes(x = year, y = gross_inv, color = category)) +
  geom_line(stat = "echo") +
  labs(x = NULL, y = NULL, color = NULL,
       title = "US Total basic infrastructure investments",
       subtitle = NULL,
       caption = "**Source:** Bureau of Economic Analysis | **Figure:** @maxwelco") +
  geom_text_repel(
    data = investment1 %>% 
                  filter(year == 2017),
    mapping = aes(color = category, label = category),
    family = "lato",
    fontface = "bold",
    size = 8,
    direction = "y",
    xlim = c(2022, NA),
    hjust = -1,
    segment.size = .7,
    segment.alpha = .5,
    segment.linetype = "dotted",
    box.padding = .4,
    segment.curvature = -0.1,
    segment.ncp = 3,
    segment.angle = 20
  ) +
  scale_y_continuous(expand = c(0.01, 0.01),
                     limits = c(0, 170000), 
                     breaks = seq(0, 170000, 20000)) +
  theme_modern_rc(base_family = "lato", base_size = 35,
                  plot_margin = margin(5, 5, 5, 5)) +
  scale_color_ft() +
  scale_x_continuous(expand = c(0.01, 0.01), 
                     limits = c(1947, 2040), 
                     breaks = seq(1950, 2020, 10)) +
  theme(legend.position = "none",
        plot.title = element_markdown(family = "staatliches", size = 55),
        plot.subtitle = element_blank(),
        plot.caption = element_markdown(size = 12)) -> fig1

ggsave("fig.png")

```



```{r}
fig1 +
    annotate("text", lineheight = .3, label = "There are eight categories of investments in basic infrastructure. Two \nclusters with four categories each have evolved since 1960. Since that,\n the gap between them has steadily increased",
                x = 1947, y = 155000, size = 10, hjust = 0) +
    annotate("text", lineheight = .3, label = "Values in million of USD",
                x = 1947, y = 85000, size = 7, hjust = 0, color = "gray80") 
#    geom_richtext(label = "There are eight categories of investments in basic infrastructure. Two \nclusters with four categories each have evolved since 1960. Since that,\n the gap between them has steadily increased", 
#                lineheight = .3,
#                x = 1947, y = 155000, size = 10, hjust = 0) +
ggsave("fig.png")
```

