---
title: "week-18"
author: "Maxwel Coura Oliveira"
date: "4/27/2021"
output: html_document
---


```{r}
library(tidyverse)
library(PupillometryR)
library(ggthemes)
library(lubridate)
```


```{r}
tuesdata <- tidytuesdayR::tt_load(2021, week = 18)
```

```{r}
departures <- tuesdata$departures
```

```{r}
departures %>% 
  arrange(leftofc)
```

```{r}
library(extrafont)
library(ggtext)
library(showtext)
showtext_auto()
font_add_google("Inder", "inder") 
```



```{r}
departures %>%
  mutate(leftofc = ymd(leftofc)) %>% 
  mutate(month = month(leftofc, label = TRUE)) %>% 
  mutate(departure = fct_recode(factor(departure_code),
                                "Death" = "1",
                                "Illness" = "2",
                                "Job performance" = "3",
                                "Legal violations or concerns" = "4",
                                "Retired" = "5",
                                "New opportunity" = "6",
                                "Other" = "7",
                                "Missing" = "8")) %>% 
  filter(fyear_gone < 2500 & !departure %in% c(NA, "9", "Missing")) -> departures1
```


```{r}
departures1 %>% 
  ggplot(aes(x = departure, y = leftofc, 
             fill = departure, 
             color = departure)) +
  geom_jitter(alpha = 0.03) +
  geom_boxplot(width = 0.2, outlier.shape = NA, alpha = 0.5) +
  geom_flat_violin(position = position_nudge(x = 0.2, y = 0), 
                   alpha = 0.8) +
  coord_flip() +
  facet_grid(~ month, switch = "x") +
  labs(x = "", y = "",
       title = "CEO Departures",
       subtitle = "Monthly distribution of reasons for CEO departure in S&P 1500 firms from 1980 through 2021",
       caption = "Source: Gentry et al. | Figure: @maxwelco") +
  theme_solarized_2() +
  scale_fill_solarized() +
  scale_color_solarized() +
  theme(legend.position = "none",
        text = element_text(family = "inder"),
        plot.title = element_markdown(family = "inder", size = 20),
        plot.subtitle = element_markdown(family = "inder", size = 11),
        plot.caption = element_markdown(size = 7),
        panel.background = element_blank(),
        strip.text = element_markdown(margin = margin(0, 0, 0, 0)),
        axis.text.x = element_blank(),
        axis.ticks = element_blank()) +
  ggsave("fig.png", width = 9, height = 5)
```





